
package com.taurus.tae.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsTae", targetNamespace = "http://tae.com/", wsdlLocation = "http://68.64.238.118/wsRecarga/wsTae?wsdl")
public class WsTae_Service
    extends Service
{

    private final static URL WSTAE_WSDL_LOCATION;
    private final static WebServiceException WSTAE_EXCEPTION;
    private final static QName WSTAE_QNAME = new QName("http://tae.com/", "wsTae");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://68.64.238.118/wsRecarga/wsTae?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTAE_WSDL_LOCATION = url;
        WSTAE_EXCEPTION = e;
    }

    public WsTae_Service() {
        super(__getWsdlLocation(), WSTAE_QNAME);
    }

    public WsTae_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTAE_QNAME, features);
    }

    public WsTae_Service(URL wsdlLocation) {
        super(wsdlLocation, WSTAE_QNAME);
    }

    public WsTae_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTAE_QNAME, features);
    }

    public WsTae_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsTae_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsTae
     */
    @WebEndpoint(name = "wsTaePort")
    public WsTae getWsTaePort() {
        return super.getPort(new QName("http://tae.com/", "wsTaePort"), WsTae.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsTae
     */
    @WebEndpoint(name = "wsTaePort")
    public WsTae getWsTaePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tae.com/", "wsTaePort"), WsTae.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTAE_EXCEPTION!= null) {
            throw WSTAE_EXCEPTION;
        }
        return WSTAE_WSDL_LOCATION;
    }

}
